<<<<<<< HEAD
include:
  - "*.xml"
  - "*.txt"
  - "*.html"
  - "*.js"
  - "*.css"

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: "sitemap.xml"
    values:
      sitemap: true

exclude:
  - README.md
  - .git/
  - .gitignore
=======
include:
  - "*.xml"
  - "*.txt"
  - "*.html"
  - "*.js"
  - "*.css"

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: "sitemap.xml"
    values:
      sitemap: true

exclude:
  - README.md
  - .git/
  - .gitignore
>>>>>>> master
  - node_modules/ 